### ISSUE TITLE
Request telemetry item that was generated during the page execution is not shown on timeline

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Glimpse/Glimpse.ApplicationInsights#17]
Request telemetry item representing the current page execution is not shown on timeline as it is generated too late. Maybe changing the order of http modules may fix this

**Comment by SergeyKanzhelev** [comment]
@JoseCarlosMM can you or somebody please take a look at this issue. It seems to be important as Request Telemetry is something that most pages will produce and you want to see what exactly will be send to the Application Insights backend.

**Comment by JoseCarlosMM** [comment]
I have tried changing the order of http modules, but it didn't fix that. I will look for other alternatives.

**Comment by SergeyKanzhelev** [comment]
Thanks @JoseCarlosMM, please keep me posted on progress. We may need to implement some workaround if it wouldn't work by simply rearranging modules.

**Comment by JoseCarlosMM** [comment]
I created a custom httpmodule and debugged the code, I realized that Glimpse httpmodule ends with the PostReleaseRequestState event and ApplicationInsights with the EndRequest event (when the current request gets called), and PostReleaseRequestState event is allways sequentially called before the EndRequest, so we can't sync both modules, also changing the order wont have any effect.

**Comment by SergeyKanzhelev** [comment]
@JoseCarlosMM can you please explain it to me. What happens when `PostReleaseRequestState` of glimpse http module got called? What if I'll call `this.messageBroker.Publish(item);` from the `End` callback - will it fail? As I understand the content of glimpse window got populated with the separate request like this: `http://localhost:55555/Glimpse.axd?n=glimpse_request&requestId=ffceba22-2b3e-47ed-b1d0-471cf4ed740b&hash=b7c6519a&callback=glimpse.data.initData` after page was loaded into the browser and ultimately after the `End` callback.

**Comment by JoseCarlosMM** [comment]
When `PostReleaseRequestState` gets called the Glimpse stops processing the Http request as shown in the `EndRequest()` in the GlimpseRuntime https://github.com/Glimpse/Glimpse/blob/b2d9b35d1bdab4d7ddd483dcf1736a0d2879c5f5/source/Glimpse.Core/Framework/GlimpseRuntime.cs method which gets called in `PostReleasRequestState` event, so everything after that will be ignored by glimpse.

**Comment by SergeyKanzhelev** [comment]
Addressed with temporary fix
